In [2]:
import numpy as np
a=np.array([1,2,3])
print("one dimensional array a=",a)
b=np.array([[1,2,3],[4,5,6]])
print("two dimensional array b=",b)
print("size of the array:",a.shape)
print("element at indices 0,1,2:",a[0],a[1],a[2])
a[0]=5
print("array after changing the element at index 0:",a)
a=np.zeros((2,2))
print("array of all zeros:",a)
b=np.ones((1,2))
print("array of all ones:",b)
c=np.full((2,2),7)
print("a constant array:",c)
d=np.eye(2)
print("a 2X2 identity matrix",d)
e=np.random.random((2,2))
print("an array with random values:",e)

one dimensional array a= [1 2 3]
two dimensional array b= [[1 2 3]
 [4 5 6]]
size of the array: (3,)
element at indices 0,1,2: 1 2 3
array after changing the element at index 0: [5 2 3]
array of all zeros: [[0. 0.]
 [0. 0.]]
array of all ones: [[1. 1.]]
a constant array: [[7 7]
 [7 7]]
a 2X2 identity matrix [[1. 0.]
 [0. 1.]]
an array with random values: [[0.33988968 0.88354136]
 [0.64463919 0.96391615]]


In [46]:
import numpy as np
print("Array indexing:slicing")
a1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("a1=",a1)
b=a1[:2,1:3]
print("sub array consisting of first two rows and columns 1 and 2:",b)
b=a1[1:2]
print("subarray consists of second row:",b)
print("Acessing columns:")
b=a1[:,1]
print(b,b.shape)
c=a1[:,1:2]
print(c,c.shape)
print("Array integer indexing: ")
a2=np.array([[1,2],[3,4],[5,6]])
print("a2=",a2)
print("Example of array indexing:",a2[[0,1,2],[0,1,0]])
print(a2[[0,0],[1,1]])
print(np.array([a2[0, 1], a2[0, 1]]))
a3=a=np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print("a3=",a3)
#Create an array of indices
b=np.array([0, 2, 0, 1])
print("b = ",b)
# Select one element from each row of a using the indices in b 
print("a3=",a3[np.arange(4), b])
#Mutate one element from each row of a using the indices in b
a3[np.arange(4), b] += 10
print("a3 = ",a3)
print("Boolean array indexing: ")
a = np.array([[1,2], [3, 4], [5, 6]])
print("a = ",a)
bool_idx= (a > 2)
print("Elements greater than 2: ",a[bool_idx])

Array indexing:slicing
a1= [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
sub array consisting of first two rows and columns 1 and 2: [[2 3]
 [6 7]]
subarray consists of second row: [[5 6 7 8]]
Acessing columns:
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)
Array integer indexing: 
a2= [[1 2]
 [3 4]
 [5 6]]
Example of array indexing: [1 4 5]
[2 2]
[2 2]
a3= [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b =  [0 2 0 1]
a3= [ 1  6  7 11]
a3 =  [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]
Boolean array indexing: 
a =  [[1 2]
 [3 4]
 [5 6]]
Elements greater than 2:  [3 4 5 6]


In [49]:
import numpy as n
x= np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[6,9], [4, 4]], dtype=np.float64)
print("x = ",x)
print("y = ",y)
print("Element wise addition: ",np.add(x, x))
print("Element wise subtraction: ",np.subtract(x, y))
print("Element wise multiplication: ",np.multiply(x, y))
print("Element wise square root of x: ",np.sqrt(x))
print("Matrix multiplication: ",np.dot(x, y))
print("Sum of all elements of matrix x: ",np.sum(x))
print("Sum of elements in each column of matrix y: ",np.sum(y,axis=0))
print("Sum of elements in each row of matrix y: ",np.sum(y,axis=1))
print("Transpose of matrix x: ",x.T)

x =  [[1. 2.]
 [3. 4.]]
y =  [[6. 9.]
 [4. 4.]]
Element wise addition:  [[2. 4.]
 [6. 8.]]
Element wise subtraction:  [[-5. -7.]
 [-1.  0.]]
Element wise multiplication:  [[ 6. 18.]
 [12. 16.]]
Element wise square root of x:  [[1.         1.41421356]
 [1.73205081 2.        ]]
Matrix multiplication:  [[14. 17.]
 [34. 43.]]
Sum of all elements of matrix x:  10.0
Sum of elements in each column of matrix y:  [10. 13.]
Sum of elements in each row of matrix y:  [15.  8.]
Transpose of matrix x:  [[1. 3.]
 [2. 4.]]


In [53]:
import numpy as np

print("Example for broadcasting: ")

v=np.array([1,2,3])

w=np.array([4,5])

print("v = ",v)

print("w = ",w)

print("Outer product of above vectors: ")

print(np.reshape(v,(3,1))*w)

x=np.array([[1,2,3],[4,5,6]])

print("x = ",x)

print("Resultant matrix after adding the vector x to each row of matrix v: ")

print(x+v)

print("Example for broadcasting fails: ")

print("Adding the vector x to each column of matrix w will generate an error")

print("Solution: Reshape the matrix w then the result will be: ")

print(x+np.reshape(w, (2,1)))

Example for broadcasting: 
v =  [1 2 3]
w =  [4 5]
Outer product of above vectors: 
[[ 4  5]
 [ 8 10]
 [12 15]]
x =  [[1 2 3]
 [4 5 6]]
Resultant matrix after adding the vector x to each row of matrix v: 
[[2 4 6]
 [5 7 9]]
Example for broadcasting fails: 
Adding the vector x to each column of matrix w will generate an error
Solution: Reshape the matrix w then the result will be: 
[[ 5  6  7]
 [ 9 10 11]]


In [2]:
from numpy import array 
from scipy.linalg import svd
A=array([[1,2],[3,4],[5,6]])
print("A=",A)
print("shape of array A:",A.shape)
print("")
U,s,VT=svd(A)
print("U=",U)
print("shape of matrix U:",U.shape)
print("")
print("Sigma (diagonal matrix),s=",s)
print("shape of matrix sigma:",s.shape)
print("")
print("transpose MATRIX,VT=",VT)
print("Shape of MATRIX VT:",VT.shape)


A= [[1 2]
 [3 4]
 [5 6]]
shape of array A: (3, 2)

U= [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
shape of matrix U: (3, 3)

Sigma (diagonal matrix),s= [9.52551809 0.51430058]
shape of matrix sigma: (2,)

transpose MATRIX,VT= [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Shape of MATRIX VT: (2, 2)


In [3]:
from numpy import array, diag, dot, zeros
from scipy.linalg import svd
A=array([[1, 2], [3, 4], [5, 6]])
print("A = ",A)

print("Shape of matrix A ",A.shape)
U,s,VT=svd(A)
print("U = ",U)
print("Shape of matrix U",U.shape)
print("Sigma diagonal matrix s=",s)
print("Shape of matrix s",s.shape)
print("VT =",VT)

print("Shape of diagonal matrix ",VT.shape)
sigma=zeros((A.shape[0],A.shape[1]))
sigma[:A.shape[1],:A.shape[1]]=diag(s)
B=U.dot(sigma.dot(VT))
print("Reconstructed matrix: ",B)


A =  [[1 2]
 [3 4]
 [5 6]]
Shape of matrix A  (3, 2)
U =  [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
Shape of matrix U (3, 3)
Sigma diagonal matrix s= [9.52551809 0.51430058]
Shape of matrix s (2,)
VT = [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
Shape of diagonal matrix  (2, 2)
Reconstructed matrix:  [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [4]:
#svd for pseudoinverse
from numpy import array, diag,zeros
from scipy.linalg import pinv
from numpy.linalg import svd
A=array([[1, 2], [3, 4],[5, 6]])
print("A = ",A)
print("Pseudoinverse of matrix A calculated by function pinv is: ")
print(pinv(A))
d=1.0/s
D=zeros(A.shape)
D[:A.shape[1],:A.shape[1]]=diag(d)
B=VT.T.dot(D.T).dot(U.T)
print("Pseudoinverse of matrix A calculated by using svd is: ")

print(B)



A =  [[1 2]
 [3 4]
 [5 6]]
Pseudoinverse of matrix A calculated by function pinv is: 
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
Pseudoinverse of matrix A calculated by using svd is: 
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
